FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src

COPY ["CarProject/CarProject.csproj", "CarProject/"]

RUN dotnet restore "CarProject/CarProject.csproj"

COPY . .

WORKDIR "/src/CarProject"

RUN dotnet build "CarProject.csproj" -c Release -o /app/build

RUN dotnet publish "CarProject.csproj" -c Release -o /app/publish /p:UseAppHost=false


FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final

WORKDIR /app

COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://+:8080

EXPOSE 8080

ENTRYPOINT ["dotnet", "CarProject.dll"]